kind: Service
apiVersion: v1
metadata:
  name: to-do-list-spring-boot-service
  namespace: spring-boot
  labels:
    app: to-do-list-spring-boot
spec:
  selector:
    app: to-do-list-spring-boot
  ports:
  - name: web
    port: 8080