apiVersion: v1
kind: Service
metadata:
  name: todo-list-spring-boot-service
  namespace: spring-boot
spec:
  selector:
    app: todo-list-spring-boot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  