apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: to-do-list-spring-boot
  namespace: spring-boot
  labels:
    app: to-do-list-spring-boot
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: to-do-list-spring-boot
  namespaceSelector:
    any: true
  endpoints:
  - port: web
    path: /actuator/prometheus
    interval: 10s