version: "3"

services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: unless-stopped

  to_do_list_spring-boot:
    image: chrystian9/to_do_list_spring-boot
    container_name: to_do_list_spring-boot
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=to-do-list-spring-boot
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=tccDevOps
    volumes:
      - /home/pramod/Desktop:/var/tmp
    depends_on:
      - db

volumes:
  postgres-data: