apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: to-do-list-quarkus-native-service-monitor
  namespace: quarkus
  labels:
    app: to-do-list-quarkus-native
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: to-do-list-quarkus-native
  namespaceSelector:
    any: true
  endpoints:
    - port: web
      path: /q/metrics
      interval: 10s