kind: Service
apiVersion: v1
metadata:
  name: to-do-list-quarkus-jvm-service
  namespace: quarkus
  labels:
    app: to-do-list-quarkus-jvm
spec:
  selector:
    app: to-do-list-quarkus-jvm
  ports:
  - name: web
    port: 8080