apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: to-do-list-quarkus-jvm-service-monitor
  namespace: quarkus
  labels:
    app: to-do-list-quarkus-jvm
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: to-do-list-quarkus-jvm
  namespaceSelector:
    any: true
  endpoints:
  - port: web
    path: /q/metrics
    interval: 10s